### ISSUE TITLE
Wintile no longer functioning under Gnome Shell 3.22.3-3/Linux 5.9.0-1-amd64/Nvidia-driver 390.138-1

### ISSUE THREAD

**Issue by Enekk** [Fmstrat/wintile#40] opened 2020-11-07 17:32 UTC
A recent update to Debian testing has left Wintile unable to do tiling.  The app still draws the blue box of where the windows will be placed, but then the window does not place.  In addition, shortcuts work to do the built-in tiling, but do not work for the corner tiling.

I had three major changes in this update:
1. Gnome Shell: 3.38.1
2. Linux: 5.9.0-1-amd64
3. Nvidia-driver: 390.138-1
4. Wintile: tag: v6

**Comment by Enekk** [comment] 2020-11-10 12:33
An update.  After a round of updates, wintile is working again with many, but not all, apps.  The big offender is Gnome Terminal (3.38.1) and I was able to reproduce it with the GUI version of Emacs (GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)) while stuff like Firefox or Slack easily tile.

**Comment by Fmstrat** [comment] 2020-11-10 13:54
What do you mean by a "round of updates"? On the GNOME side?

**Comment by Enekk** [comment] 2020-11-10 16:11
Some of the updates were Gnome related (running Debian testing).

**Comment by iamklaus** [comment] 2020-11-22 09:57
Any idea where what the problem of the terminal behaviour is coming from? Geary (Mail Client) shows the same behaviour as the terminal, but most application work, many thanks!

**Comment by Enekk** [comment] 2020-11-23 02:01
I'm happy to experiment if @Fmstrat has anything that would be useful.  Maybe I can turn logging on (where are those stored?) and see if anything shows up?

**Comment by pedrojorgedev** [comment] 2021-01-16 16:49
I am experiencing the same bugs with the gnome terminal. Tried other terminal emulators like xterm and terminology and the problem persisted. Installed the GUI version of Emacs to confirm after reading this, same problem.

**Comment by NeroProtagonist** [comment] 2021-01-28 16:47
Gnome Terminal doesn't work for me either on Ubuntu 20.04.

**Comment by cascremers** [comment] 2021-01-28 17:39
It looks like the thing I fixed at #49, let me know if that works for you.

**Comment by pedrojorgedev** [comment] 2021-01-28 17:42
> It looks like the thing I fixed at #49, let me know if that works for you.

@cascremers I replied just that in your pull request! Can you tell me how to try the changes in my own machine, so I can report back?

**Comment by cascremers** [comment] 2021-01-28 18:19
> > It looks like the thing I fixed at #49, let me know if that works for you.

> @cascremers I replied just that in your pull request! Can you tell me how to try the changes in my own machine, so I can report back?

My change only involves the file `extension.js`, if you copy [my version](https://raw.githubusercontent.com/Fmstrat/wintile/7dac8cb5f79e4c5fcd58378698d85c050164b758/extension.js) over your own local copy, which should be in this directory:

`~/.local/share/gnome-shell/extensions/wintile@nowsci.com`

and then log out and log back in, you should be running the updated version.

**Comment by pedrojorgedev** [comment] 2021-01-28 18:31
> > > It looks like the thing I fixed at #49, let me know if that works for you.
> 
> > @cascremers I replied just that in your pull request! Can you tell me how to try the changes in my own machine, so I can report back?
> 
> My change only involves the file `extension.js`, if you copy [my version](https://raw.githubusercontent.com/Fmstrat/wintile/7dac8cb5f79e4c5fcd58378698d85c050164b758/extension.js) over your own local copy, which should be in this directory:
> 
> `~/.local/share/gnome-shell/extensions/wintile@nowsci.com`
> 
> and then log out and log back in, you should be running the updated version.

Done that and it is now working as intended. I support this fix @Fmstrat

**Comment by ba32107** [comment] 2021-01-31 17:17
Fixed in https://github.com/Fmstrat/wintile/pull/49, will be released by @Fmstrat. For now, the fix can be applied manually by checking out the `develop` branch.

**Closed by ba32107** 2021-01-31 17:17 UTC
