### ISSUE TITLE
Corner tile, using mouse to open context menu or sub-window causes window to revert

### ISSUE THREAD

**Issue by jamesrbarker** [Fmstrat/wintile#34] opened 2020-10-10 12:59 UTC
Greetings,

I"m loving this extension, however I may have found a bug.

WHAT HAPPENS (100% reproducible):
+ Move window to corner (quarter tile) (eg: nautilus, gedit, etc..)
+ Right click and select "Properties" or any item which will cause a sub-window to open.
+ Immediately, the window will be pulled out of the corner tile position, and extend partially off screen.
Sometimes this occurs as soon as the right click / context menu opens.
Sometimes this occurs as I'm moving my mouse toward the context menu's "Properties" text. 

WORKAROUND:
Interestingly, this issue does NOT OCCUR if I use the keyboard to navigate:
+ Move window to corner (with mouse or keyboard) (quarter tile again)
+ {Shift}+[F10] to open context menu, use keyboard to select/open "Properties", etc..
+ The sub-window opens normally and the original window remains in place.

In another bug report, there was mention of the mouse movement of my first example as possibly being a contributing factor. (https://github.com/Fmstrat/wintile/issues/17)

OS and VERSIONS:
Dell XPS 13 (9360) Kaby Lake
Intel® Core™ i7-7500U CPU @ 2.70GHz × 4 
Graphics: Mesa Intel® HD Graphics 620 (KBL GT2)
Ubuntu 20.04.1 LTS
Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Gnome 3.36.3
Wayland 1.18.0-1 (focal)
Nautilus 3.26.3 stable
WinTile v6

Let me know how I can help troubleshoot.
-James

**Comment by Fmstrat** [comment] 2020-10-10 13:10
What is your delay set to? And does increasing it to 500ms fix this?

**Comment by jamesrbarker** [comment] 2020-10-10 13:14
Ben,

"Delay in ms before preview displays" was set to 100ms.  I changed it to
500ms and the issue persists.
J

**Comment by ba32107** [comment] 2020-10-10 15:06
Hi @jamesrbarker, I'm having trouble following your reproduction steps and understanding exactly what the issue is. Is this the same problem described in [this](https://github.com/Fmstrat/wintile/issues/20#issuecomment-674899324) comment? There is a  link to a screencast - is this the issue you're describing?

**Comment by Fmstrat** [comment] 2020-10-10 15:18
I wonder if this is an issue with Wayland interactions? That's the only system difference I can think of. Perhaps it's interpreting the "properties" click as a "window" click.

**Comment by jamesrbarker** [comment] 2020-10-11 11:16
Ben & Balazs,

Thanks for the reply!  I looked at the other ticket's issue.  I'm affected by that issue, however the issue I reported seems to be different.  I've linked a video of my issue.  https://streamable.com/wjgjgp  You'll see that the tiled window behaves erratically as soon as I open the context menu and then begin to move my mouse toward any of the context menu's items.  In the video I repeat it a few times before using the keyboard to navigate -- the latter which works as expected.

Also, I was only able to reproduce the issue under Wayland.  Switching to X resulted in normal behavior.
J

**Comment by ba32107** [comment] 2020-10-12 20:32
Ah right, I understand now, I did do the same repro steps, but because I use X, it didn't happen. Looks like this is a Wayland-only issue.

**Comment by ba32107** [comment] 2020-10-12 20:36
Also I'm pretty sure this is the same issue as #17 (as you mentioned)

**Comment by jamesrbarker** [comment] 2020-10-13 09:36
Excellent, thank you for looking into this for me!
J

**Comment by ba32107** [comment] 2020-10-13 19:34
I will take a look at some point but can't promise anything as I'm not familiar with Wayland at all

**Comment by zb3** [comment] 2020-12-19 18:04
I'm not sure whether this is the same bug, but it appears that Wayland emits a grab event when a popup menu is opened. That one can however be distinguished from other grab events by checking `meta_grab_op`. In my fix below, I simply ignore grab events in that case, see:
https://github.com/zb3/wintile/commit/ec0041a7fd5cf64fd63d56251a816f610534dfdf

**Comment by wiebe** [comment] 2021-01-31 21:33
@zb3 That is the same bug and i can confirm your fix works :+1: Maybe you could do a pull request so that it can be merged? :-)

**Comment by Fmstrat** [comment] 2021-02-01 14:53
@zb3 Would you like to do a PR? If so, I'll hold on doing this fix.

**Comment by zb3** [comment] 2021-02-01 15:58
@Fmstrat @wiebe done, I've submitted a PR.

**Comment by derrgill** [comment] 2021-02-06 16:17
I'm having this same problem on Manjaro using Wayland, but just one small clarification. I have my mouse buttons reversed, so my _secondary_ click in this case is a left click. I have a Nautilus window tiled to a corner, and when I secondary click on a folder to view properties, this causes the tiled window to become untiled.

**Closed** 2021-04-29 13:46 UTC
