### ISSUE TITLE
don't overwrite the default manual size

### ISSUE THREAD

**Issue by 14kaitou** [Fmstrat/wintile#44] opened 2020-12-15 18:13 UTC
Hi, I want to ask? this is a very extreme tiling that's fast and reliable but, it overwrites my default size with the last tiling size, can there be an option to save the size that I set so don't get overwrites by the extensions or add it to the new feature, for consideration?.

- extension on 

super+something to till, then I double click on the window panel or minimize+maximize button but it back to the last tilling size. 
    
- extension off

like above but it gets back to the default size that I manually set

**Comment by ba32107** [comment] 2020-12-15 18:39
I believe this is a duplicate of https://github.com/Fmstrat/wintile/issues/20

**Closed** 2020-12-15 19:35 UTC
