### ISSUE TITLE
Pop-up menus cause windows to revert

### ISSUE THREAD

**Issue by nemequ** [Fmstrat/wintile#17] opened 2020-01-18 22:45 UTC
If you use wintile to put a window of a GTK+ program somewhere, then right click to bring up a context window, as soon as you move the mouse (like to select an item) the window will revert to its previous placement.

I'm hitting this constantly in GNOME Terminal (for copy and paste), but I just tested GEdit and the problem exists there as well.

This worked before the latest update.  I'm not absolutely certain that it wasn't a GNOME update or something that broke it, but the timing of the wintile update is pretty suspicious…

This is with Fedora 31 with all updates applied.

**Comment by ba32107** [comment] 2020-01-20 07:21
Hmm, works perfectly for me on Ubuntu 19.10. This is what I did:
1. Open terminal
1. Move it to the bottom left corner with the hotkeys
1. Right click and select 'Always on top'

Works fine. Could you share your Wintile settings?

**Comment by nemequ** [comment] 2020-01-21 20:54
I'm using the default settings, this happens with a fresh install.  And before the install I made sure ~/.gnome-shell/extensions/wintile@nowsci.com/ didn't exist.

Something is definitely odd.

I do Win + → and the Window takes up not quite half the screen on the left side (there is about a 5% margin to the left of the window).

Press it again and it moves the window to the right half but still doesn't take up the whole half (the margin is on the right side now), but a copy of the old window is still visible where it was before (the contents in that copy don't update when changes are made to the window on the right).

Win + ↓ and the window is displayed correctly only in the bottom right corner. but I have the right-click issue.

The old version worked perfectly for me.

**Comment by Fmstrat** [comment] 2020-01-21 21:29
@nemequ 

I don't have a Fedora 31 handy, but can you turn on debug in the prefs:
```
gnome-shell-extension-prefs wintile@nowsci.com
```

And then send me the output of:
```
xrandr > xrandr.log
journalctl -qf > journalctl.log
```
The `journalctl` will not exit. While it is running, do whatever it is that breaks, then if you could `Cntrl-C` and annotate the log file a bit to tell me when you're doing what it would be helpful.

Thanks!

**Comment by nemequ** [comment] 2020-01-22 01:22
Of course, thanks for looking at this.

xrandr:

```
Screen 0: minimum 16 x 16, current 3840 x 2160, maximum 32767 x 32767
XWAYLAND0 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   3840x2160     59.96*+
   2048x1536     59.95  
   1920x1440     59.90  
   1600x1200     59.87  
   1440x1080     59.87  
   1400x1050     59.86  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.78  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   2560x1600     59.94  
   1920x1200     59.88  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.20  
   320x200       58.96  
   3200x1800     59.96  
   2880x1620     59.92  
   2560x1440     59.91  
   2048x1152     59.90  
   1920x1080     59.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77
```

journald, Win + →

```
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], ---
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], sendMove: right
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], monitorToLeft: -1
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], monitorToRight: -1
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], Not in tile.
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], initApp
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], init as normal
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], moveApp: {"row":0,"col":1,"height":2,"width":1}
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], maximize - v
Jan 21 16:24:58 peltast gnome-shell[1831]: [WinTile], window.x: 1109 window.y: 694 window.width: 1670 window.height: 949
```

Window is now maximized vertically, but horizontal position unchanged.

Win + →

```
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], ---
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], sendMove: right
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], monitorToLeft: -1
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], monitorToRight: -1
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], Already in a tile.
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], {"origFrame":{},"row":0,"col":1,"height":2,"width":1}
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], right
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], right - 4
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], moveApp: {"row":0,"col":1,"height":2,"width":1}
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], maximize - v
Jan 21 16:25:05 peltast gnome-shell[1831]: [WinTile], window.x: 1109 window.y: 27 window.width: 1670 window.height: 2133
```

Now the window is the same width as before, but the left edge is centered on the screen.  The contents of the old window are still visible at their old position, and it remains there even when changing virtual desktops.

Win + ↓:

```
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], ---
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], sendMove: down
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], monitorToLeft: -1
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], monitorToRight: -1
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], Already in a tile.
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], {"origFrame":{},"row":0,"col":1,"height":2,"width":1}
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], down
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], down - 3
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], moveApp: {"row":1,"col":1,"height":1,"width":1}
Jan 21 16:25:10 peltast gnome-shell[1831]: Error in size change accounting.
Jan 21 16:25:10 peltast gnome-shell[1831]: [WinTile], window.x: 1920 window.y: 27 window.width: 1670 window.height: 2133
Jan 21 16:25:10 peltast gnome-shell[1831]: Error in size change accounting.
```

The window now occupies the bottom right quarter of the screen (which is what I wanted), and the old window is no longer visible.

Right click:

```
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], windowGrabBegin
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], checkForMove
```

Note that this message keeps repeating until I move the mouse.

Move the mouse slightly:

```
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], restoreApp
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], false
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], {"origFrame":{},"row":1,"col":1,"height":1,"width":1}
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], A) mouse - x:2400 y:1455
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], A) window - x:1920 y:1093 w:1918 h:1057
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], A) origFrame - x:1109 y:694 w:1670 h:949
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], B) mouse - x:2400 y:1455
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], B) window - x:1920 y:1093 w:1918 h:1057
Jan 21 16:25:17 peltast gnome-shell[1831]: [WinTile], B) origFrame - x:1109 y:694 w:1670 h:949
Jan 21 16:25:20 peltast gnome-shell[1831]: [WinTile], windowGrabEnd
```

Window restored to original size and position.

Hopefully that helps, let me know if you need anything else.

**Comment by Fmstrat** [comment] 2020-02-06 12:01
Ok, that gives me a lot more info. For some reason Fedora is reporting a window drag when using the right mouse button. Are you "right clicking" or "right click hold a dragging" to get to the menu option?

**Comment by nemequ** [comment] 2020-02-06 16:45
Just right click.  I release the mouse button immediately without moving the mouse at all and the pop-up appears, but as soon as I do move the mouse (with neither button depressed) the window is restored.

**Comment by ba32107** [comment] 2020-10-12 20:39
This seems to be an issue in Wayland only. It's a duplicate of https://github.com/Fmstrat/wintile/issues/34

**Closed by ba32107** 2020-10-12 20:39 UTC
Labels: bug
