### ISSUE TITLE
Terminal window leaves gap in Ubuntu 22.04

### ISSUE THREAD

**Issue by LeonEricsson** [Fmstrat/wintile#180] opened 2024-02-02 08:29 UTC
Hi,
I've got the gap option set to 0 (note how the firefox windows don't have any gaps in the image) but my terminal windows still leave an unwanted gap. Ubuntu 22.04.03. GNOME 42.9

![image](https://github.com/Fmstrat/wintile/assets/70749762/e73b682f-a088-4419-9d4a-56100b656486)

**Comment by GrylledCheez** [comment] 2024-02-02 11:03
If the terminal is GNOME Terminal, then this is a duplicate of #162.

**Comment by LeonEricsson** [comment] 2024-02-02 11:59
> If the terminal is GNOME Terminal, then this is a duplicate of #162.

It's the default terminal application on Ubuntu 22.04, so I guess so? I'll close this if that's the case.

**Closed** 2024-02-04 20:26 UTC
